version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: react_oms_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgreSQL
    networks:
      - laravel

  # mysql:
  #   image: mysql:5.7.29
  #   container_name: react_oms_mysql
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: rbuzzeroffice
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   networks:
  #     - laravel

  postgreSQL:
    image: "postgres" # use latest official postgres version
    container_name: react_oms_postgresql
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rbuzzeroffice
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: postgreSQL
    networks:
      - laravel

  # pgadmin:
  #   container_name: react_pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: rujyi94@hotmail.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "8081:81"
  #   networks:
  #     - laravel
  #   restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_oms_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: react_oms_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: react_oms_npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_oms_artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgreSQL
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
